#+TITLE: Blog Posts
#+author: Jay Paul Morgan
#+include: ./template.org
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/css/index.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://blog.morganwastaken.com/css/index.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/index.css"/>
#+HTML_HEAD: <meta name="description" content="A collection of blog posts and articles published by Dr. Jay Paul Morgan.">

#+begin_src emacs-lisp :results output raw :exports results :eval yes
  (defun get-posts (dir)
    "Get a list of relative paths to the posts"
    (cl-reduce
     (lambda (files filepath)
       (let ((filename (car (last (split-string filepath "/")))))
	 (if (string= filename "index.org")
	     files
	   (cons filepath files))))
     (directory-files-recursively dir ".*\.org")
     :initial-value nil))

  (defun read-title-from-post (filepath)
    (with-temp-buffer
      (insert-file-contents filepath)
      (re-search-forward "^#\\+\\(TITLE\\|title\\):")
      (buffer-substring-no-properties (1+ (point)) (point-at-eol))))

  (defun read-summary-from-post (filepath)
    (with-temp-buffer
      (insert-file-contents filepath)
      (format "%s..."
       (substring
	(string-trim
	 (replace-regexp-in-string
	  "\\*+ " ""
	  (replace-regexp-in-string "#\\+\\(TITLE\\|AUTHOR\\|DATE\\|INCLUDE\\):.*\n" "" (buffer-string))))
	0
	300))))

  (dolist (post (get-posts "./posts"))
    (princ (format "- [[%s][%s]]\n\n#+begin_quote\n%s\n#+end_quote\n\n" post (read-title-from-post post) (read-summary-from-post post))))
#+end_src

#+RESULTS:
- [[./posts/2023-03-18-Org-babel-remote-images/remote.org][Displaying remote images in Org-mode]]

#+begin_quote
In one of my [[file:../2022-12-15-org-babel-tramp/org-babel-tramp.org][previous posts]], I explained how a remote python process
can be setup in an org-mode documents. Therefore, allowing you to
offload any large compute to a remote server.

However, in the previous post, I mentioned how I was unabl...
#+end_quote

- [[./posts/2022-12-15-org-babel-tramp/org-babel-tramp.org][Using a remote Python process in Org-mode files]]

#+begin_quote
Introduction

Sometimes the work we do requires a lot of horse-power -- a lot of compute
resource. Perhaps more than what we can do locally. In these cases, we might need to
use a remote server.

In this blog post, I wanted to demonstrate how I've used a local org-mode file to
execute computations v...
#+end_quote

- [[./posts/2022-12-09-singularity/2021-02-22-enter-the-singularity.org][Enter the Singularity Or Containers for Reproducible Research Environments]]

#+begin_quote
We must have all said at some point 'But it works on my machine'. The intricacies and
details surrounding some program that /should/ work on another machines, but ultimately
doesn't. Docker solves this problem in business environments by shipping your
machine, and maybe this method is a brilliant st...
#+end_quote

- [[./posts/2022-10-12-adaptive/adaptive-neighbourhoods.org][XTAI 2022 - Adaptive Neighbourhoods for the Discovery of Adversarial Examples]]

#+begin_quote
#+options: toc:nil

Talk prepared for the AISB Workshop on Explainability and Transparency in AI,
XTAI 2022.

*Presentation Abstract*

Machine Learning, in particular Deep Learning, has most recently
provided the state-of-the-art results for many tasks such as object
recognition, text-to-speech proc...
#+end_quote

- [[./posts/2021-03-29-bctcs/bctcs-conf.org][British Colloquium for Theoretical Computer Science (BCTCS) 2021]]

#+begin_quote
#+options: toc:nil

**Presentation Abstract**

Machine Learning (ML) has had a remarkable impact on society. Everything from the
phones in our pockets, to the cars that we drive, are being increasingly outfitted
with this progressively sophisticated suite of algorithms. But while many of the most
ba...
#+end_quote

- [[./posts/2020-03-05-makefile/makefile.org][Makefile: Towards Reproducible Research-based Programming]]

#+begin_quote
I've been experimenting with =make= to deliver research projects. It has been to
be a great way to alleviate some particular pain points that
arise from these types of projects. Sufficed to say, the =make= tool has
been an excellent addition to my workflow, one that I shall continue
to use and exper...
#+end_quote

- [[./posts/2019-06-27-membership-functions/membership-functions.org][Fuzzy Logic Membership Functions]]

#+begin_quote
#+PROPERTY: header-args:python :eval never-export

A membership function is a method of translating a crisp value $x \in
\mathbb{R}$ into a fuzzy set. In other words, we can find the
membership grade (the amount of membership) for x with a value between
0 and 1. If the membership grade is only 0 or ...
#+end_quote


